{
  parserClass="com.github.baeyung.poslang.statelang.parser.StateParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.baeyung.poslang.statelang.psi"
  psiImplPackage="com.github.baeyung.poslang.statelang.psi.impl"

  elementTypeHolderClass="com.github.baeyung.poslang.statelang.psi.StateTypes"
  elementTypeClass="com.github.baeyung.poslang.statelang.type.StateElementType"
  tokenTypeClass="com.github.baeyung.poslang.statelang.type.StateTokenType"
  psiImplUtilClass="com.github.baeyung.poslang.statelang.utils.psi.StatePsiImplUtil"
}

file ::= element*

element ::= tag | commentTag

tag ::= pairedTag | emptyTag

pairedTag ::= startTag tagBody endTag

tagBody ::= content*

content ::= tag | commentTag | text

text ::= TEXT

tagName ::= TAG_NAME

attributeName ::= IDENTIFIER

attributeValue ::= STRING

attributeList ::= attribute*

startTag ::= OB tagName attributeList? CB {
    methods=[ getName ]
}

endTag ::= OB_SLASH tagName CB {
    methods=[ getName ]
}

emptyTag ::= OB tagName attributeList? SLASH_CB {
   methods=[ getName ]
}

attribute ::= attributeName EQ attributeValue {
    methods=[ getKey getValue ]
}

commentTag ::= COMMENT
