{
  parserClass="com.github.baeyung.poslang.statelang.parser.StateParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.baeyung.poslang.statelang.psi"
  psiImplPackage="com.github.baeyung.poslang.statelang.psi.impl"
  elementTypeHolderClass="com.github.baeyung.poslang.statelang.psi.StateTypes"
  elementTypeClass="com.github.baeyung.poslang.statelang.type.StateElementType"
  tokenTypeClass="com.github.baeyung.poslang.statelang.type.StateTokenType"
  psiImplUtilClass="com.github.baeyung.poslang.statelang.utils.psi.StatePsiImplUtil"
}

file ::= rootElement*
private rootElement ::= tag | commentTag {
    recoverWhile=file_recover
}

private file_recover ::= !(OB | OB_SLASH | COMMENT)

tag ::= pairedTag | selfClosingTag {
    pin=1
}

pairedTag ::= startTag tagBody endTag {
    methods=[ getStartTagName getEndTagName ]
}

tagBody ::= content* {
    recoverWhile=tagBody_recover
}

private tagBody_recover ::= !(OB_SLASH | OB | COMMENT)

selfClosingTag ::= OB tagNameEl attributeList? SLASH_CB {
    methods=[ getTagName ]
}

startTag ::= OB tagNameEl attributeList? CB {
    methods=[ getTagName ]
}

endTag ::= OB_SLASH tagNameEl CB {
    pin=2
    methods=[ getTagName ]
}

tagNameEl ::= TAG_NAME

attributeList ::= attribute+

attribute ::= attributeName EQ attributeValue {
    pin=1
    mixin="com.github.baeyung.poslang.statelang.type.StateNamedElementImpl"
    implements="com.github.baeyung.poslang.statelang.type.StateNamedElement"
    methods=[ getKey getValue getNameIdentifier getName setName ]
}

attributeName ::= IDENTIFIER
attributeValue ::= STRING
content ::= tag | commentTag
commentTag ::= COMMENT